### ISSUE TITLE
:sync="true" doesn't work?

### ISSUE THREAD

**Issue by soichih** [dhenkes/vue2-ace#5]
I've set `:sync="true"` but when I update the text on editor, the content doesn't get synchronized to the original variable.

I am using <editor> inside another component, and I wonder if that is the cause of this issue..

```
<el-form>
    <el-form-item>
        <editor :content="form._config" :sync="true" :lang="'json'"></editor>
    </el-form-item>
</el-form>
```

**Comment by dhenkes** [comment]
Sorry for the late reply, but did you include the following code into your application?

```
mounted () {
  var vm = this;
  vm.$on('editor-update', vm.function);
}
```

Sync currently only tells the application that as soon as the original variable gets updated, it should also update the text in the editor. It does not update the origin variable.

To update the origin variable you need to include the code above and use vm.function (that should be a function in your app) to update the variable. Something like this would be possible:

```
methods: {
  update (value) {
    var vm = this;
    vm.myOriginVariable = value;
  } 
},

mounted () {
  var vm = this;
  vm.$on('editor-update', vm.function);
}
```

Let me know if it worked or if I can help any further.

I'm currently working on an easier way to auto update the variable.
